  <div class="page-content">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <span class="divider">/</span></li>
            <li class="active">Ошибка 404</li>
          </ul>
        </div>
      </div>
      
      <div class="row-fluid">
        <h1>Ошибка 404 - страница не найдена</h1>

        <p>Страница не найдена. Возможно, она была удалена, перемещена или вовсе не сущестовала. Возможно, Вы сможете найти искомое в нашем <a href="/category" />каталоге</a></p>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
      </div>
    </div>
  <div>
