  <div class="page-content">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <span class="divider">/</span></li>
            <li class="active">Ошибка 500</li>
          </ul>
        </div>
      </div>
      
      <div class="row-fluid">
        <h1>Ошибка 500</h1>

        <p>На сайте произошла ошибка. Ближайшее время, она будет исправлена. А пока Вы можете посетить наш <a href="/category" />каталог</a></p>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
      </div>
    </div>
  <div>
