    <div id="footer">
      <div class="container">
        <div class="row-fluid">
          <div class="span12">
            <h3>Protein Lab</h3>
            <p>Лучшее спортивное питание из США. Прямые поставки, отличное качество, демократичные цены</p>
            <div class="icon">
              <span class="twitter"><a href="https://twitter.com/ProteinLabUa" class="social-icon" target="_blank"><i class="icon-twitter"></i></a></span>
              <span class="linkedin"><a href="http://vk.com/proteinlab" class="social-icon" target="_blank"><i class="icon-vk"></i></a></span>
              <span class="facebook"><a href="https://www.facebook.com/proteinlabua" class="social-icon" target="_blank"><i class="icon-facebook"></i></a></span>
              <!-- <span class="google"><a href="" class="social-icon"><i class="icon-google-plus"></i></a></span> -->
            </div>
            <div class="sitemap">
              <ul>
                <li><a href="/">ГЛАВНАЯ</a></li>
                <li><a href="/about">О НАС</a></li>
                <li><a href="/contacts">КОНТАКТЫ</a></li>
                <li><a href="/delivery">Оплата и доставка</a></li>
                <li><a href="/blog">Блог</a></li>
                <li><a href="/category">Категории товаров</a></li>
                <li><a href="/manufacturer">Производители</a></li>
                <li><a href="/rules">Правила</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="copyright">
      <div class="container">
        <div class="row-fluid">
          <div class="span12">
            <small>Copyright &copy; 2014 ProteinLab All Right Reserved. 
          </div>
        </div>
      </div>
    </div>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-9869100-18', 'proteinlab.com.ua');
      ga('require', 'displayfeatures');
      ga('send', 'pageview');
    </script>
    <script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter24639989 = new Ya.Metrika({id:24639989}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/24639989" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
  </body>
</html>