<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title><?php if($title) echo $title, ' - '; ?>Интернет-магазин PROTEIN LAB - лучшее спортивное питание из США</title>
    <meta name="description" content="<?php if(isset($description)): ?><?php echo $description; ?><?php endif;?>" />
    <meta name="keywords" content="<?php if(isset($keywords)): ?><?php echo $keywords; ?><?php endif;?>" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="1YxS584sWoVnb0Qq-leNp6e2POUF_nRuWURtKNOHpSY" />
    <meta name='yandex-verification' content='4449b6e523b0e298' />
    
    <link rel="stylesheet" href="/css/bootstrap.min.css" >
    <link rel="stylesheet" href="/css/bootstrap-responsive.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <!--[if IE 7]><link rel="stylesheet" href="/css/font-awesome-ie7.min.css"><![endif]-->
    <!--[if lt IE 9]><script src="/js/plugins/html5.js"></script><![endif]-->
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
    <script src="/js/vendor/jquery/jquery.min.js"></script>
    <script src="/js/vendor/bootstrap/bootstrap.min.js"></script>
    <script src="/js/vendor/backbone/underscore.js"></script>
    <script src="/js/plugins/jquery.mask.min.js"></script>
    <script src="/js/plugins/jquery.mixitup.min.js"></script>
    <script src="/js/script.js"></script>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse collapse navbar-responsive-collapse">
            <ul class="nav nav-left">
              <!-- <li <?php if($page === 'index'): ?>class="active"<?php endif; ?>><a href="/">ГЛАВНАЯ</a></li> -->
              <li class="dropdown <?php if($page === 'catalogue' || $page === 'catalogue-item'): ?>active<?php endif; ?>">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">КАТАЛОГ ПРОДУКЦИИ <b class="caret"></b></a>
                <ul class="dropdown-menu animated fadeInUp">
                  <?php foreach($categories as $category): ?>
                    <li><a href="/category/<?php echo $category->slug; ?>"><?php echo $category->name; ?></a></li>
                  <?php endforeach; ?>
                  <li class="divider"></li>
                  <?php foreach($manufacturers as $manufacturer): ?>
                    <li><a href="/manufacturer/<?php echo $manufacturer->slug; ?>"><?php echo $manufacturer->name; ?></a></li>
                  <?php endforeach; ?>
                </ul>
              </li>
              <li <?php if($page === 'about'): ?>class="active"<?php endif; ?>><a href="/about">О НАС</a></li>
              <li <?php if($page === 'blog' || $page === 'blog-item'): ?>class="active"<?php endif; ?>><a href="/blog">БЛОГ </a></li>     
              
            </ul>
            <a href="/" class="logo visible-desktop"><img src="/img/logo.jpg" alt="dodolan manuk responsive catalog themes"></a>
            <div id="brand" class="visible-desktop">&nbsp;</div>
            <ul class="nav nav-right" style="margin-left: 0">        
              <li <?php if($page === 'contacts'): ?>class="active"<?php endif; ?>><a href="/contacts">КОНТАКТЫ</a></li> 
              
              <!-- <li class="dropdown <?php if($page === 'order' || $page === 'order-confirm'): ?>active<?php endif; ?>" style="margin-left:10px">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">КОРЗИНА (<span class="orderCount"><?php echo $orderCount; ?></span> на <?php echo $total; ?> грн.) <b class="caret"></b></a>
                <ul class="dropdown-menu animated fadeInUp">
                  <?php if(count($order) > 0): ?>
                    <?php foreach($order as $item): ?>
                      <li style="font-size:11px;padding:5px 5px 0 5px"><span><?php echo $item['product']->name; ?> (<?php echo $item['weight']['name']; ?> <?php if($item['weight']['type'] == 'gramm'): ?>г.<?php else: ?>таб.<?php endif; ?>) <?php echo $item['count']; ?> шт. -  <b><?php echo $item['price']; ?> грн.</b></span></li>
                    <?php endforeach; ?>
                  <li class="divider"></li>
                  <li style="text-align:center"><a href="/order">Оформить заказ</a></li>
                  <?php else: ?>
                    <li style="padding:5px;text-align:center">Корзина пуста</li>
                  <?php endif; ?>
                </ul>
              </li> -->
              <li <?php if($page === 'order' || $page === 'order-confirm'): ?>class="active"<?php endif; ?>><a href="/order">КОРЗИНА (<span class="orderCount"><?php echo $orderCount; ?></span> на <span class="orderTotal"><?php echo $total; ?></span> грн.)</a></li>
              
            </ul>
          </div><!-- /.nav-collapse -->
        </div>
      </div><!-- /navbar-inner -->
    </div>
    <?php //if($page == 'index'): ?>
      <div id="masthead">
        <div id="slider" class="carousel slide carousel-fadein">
          <ol class="carousel-indicators">
            <li data-target="#slider" data-slide-to="0" class="active"></li>
            <li data-target="#slider" data-slide-to="1" class=""></li>
            <li data-target="#slider" data-slide-to="2" class=""></li>
          </ol>
          <div class="carousel-inner">
            <div class="item active">
              <img src="/img/s11.jpg" alt="">
                <div class="container">
                <div class="carousel-caption">
                  <h2>Акция!</h2>
                  <p class="lead">Creatine 2500 Caps (100 капсул) от ON всего за <span class="masterprice">349 грн.</span>! <br/>Закажите сейчас и получите в подарок OPTIMUM NUTRITION PRO BCAA 8g!
                  </p>
                  <a class="btn btn-large btn-warning" href="/item/creatine-2500-caps-optimum-nutrition">Купить сейчас</a>
                </div>
              </div>
            </div>
           <div class="item ">
              <img src="/img/s22.jpg" alt="">
              <div class="container">
              <div class="carousel-caption">
                <h2>Акция!</h2>
                <p class="lead">Уникальная цена! Syntha-6 1320 г. всего за <span class="masterprice">799 грн.</span>! <br/>Спешите купить товары по старому курсу доллара!</p>
                <a class="btn btn-large btn-warning" href="/item/syntha-6-bsn">Купить сейчас</a>
              </div>
              </div>
            </div>
            <div class="item">
              <img src="/img/s33.jpg" alt="">
              <div class="container">
              <div class="carousel-caption">
                <h2>Акция!</h2>
                <p class="lead">100% Whey Protein от OPTIMUM NUTRITION всего за <span class="masterprice">769 грн.</span>! <br/>Спешите купить товары по старому курсу доллара!</p>
                <a class="btn btn-large btn-warning" href="/item/100-whey-protein-optimum-nutrition">Купить сейчас</a>
              </div>
              </div>
            </div>
          </div>
          <!-- <a class="left carousel-control" href="#slider" data-slide="prev">&lsaquo;</a>
          <a class="right carousel-control" href="#slider" data-slide="next">&rsaquo;</a> -->
        </div>
      </div>
    <?php //else: ?>
      <!-- div class="heads">
        <div class="container">
          <div class="row-fluid">
            <div class="span12">
              <h2><span>//</span> <?php echo $title ?></h2>  
            </div>
          </div>
        </div>
      </div> -->
    <?php //endif; ?>