<div class="row-fluid products">
  <h1>Сообщения пользователей</h1>
  <hr/>
  <p>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>ФИО</th>
          <th>EMAIL</th>
          <th>Тема</th>
          <th>Сообщение</th>
          <th>Дата</th>
        </tr>
      </thead>
      <?php foreach($feedbacks as $feedback): ?>
      <tr>
        <td><?php echo $feedback->id; ?></td>
        <td><?php echo $feedback->name; ?></td>
        <td><?php echo $feedback->email; ?></td>
        <td><?php echo $feedback->subject; ?></td>
        <td><?php echo $feedback->body; ?></td>
        <td><?php echo date('d M Y', $feedback->time); ?></td>
      </tr>
      <?php endforeach; ?>
    </table>
  </p>
</div>