<?php include_once __DIR__.'/inc/header.phtml'; ?>
    <div class="container">
      <form class="form-signin" action="/admin/login" method="post">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="input-block-level" placeholder="Email address" name="email">
        <input type="password" class="input-block-level" placeholder="Password" name="password">
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
      </form>
    </div><!-- /container -->