
  <div class="page-content">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <span class="divider">/</span></li>
            <li class="active">О нас</li>
          </ul>
        </div>
      </div>
      
      <div class="row-fluid">
        <div class="span12 t-center">
          <h3>Интернет магазин спортивного питания ”PoteinLab”</h3>
          <p>Мы занимается продажей спортивного питания по всей Украине. Почему мы лучшие? На это есть три причины:</p>
        </div>
      </div>

      <div class="row-fluid padd20-top-btm">
        <div class="span8">
          <h3>Специалисты</h3>
          <p>В состав нашей компании входят квалифицированные специалисты, которые отдали много лет спорту и поймут вас с полуслова.</p>
        </div>
        <div class="span4">
          <img src="/img/111.jpg" alt="dodolan manuk catalogue">
        </div>
      </div>
      
      <div class="row-fluid padd20-top-btm">
        <div class="span4">
          <img src="/img/usa2.png" alt="dodolan manuk catalogue">
        </div>
        <div class="span8">
          <h3>Качество</h3>
          <p>Вся наша продукция поставляется исключительно из США. Мы работаем напрямую с производителями. Поэтому вы всегда можете быть уверены, что приобретёте продукцию наивысшего качества по лучшим ценам.</p>
        </div>
      </div>

      <div class="row-fluid padd20-top-btm">
        <div class="span8">
          <h3>Обратная связь</h3>
          <p>Мы всегда открыты к критике и предложениям. Мы хотим совершенствоваться!</p>
        </div>
        <div class="span4">
          <img src="/img/feedb.jpg" alt="dodolan manuk catalogue">
        </div>
      </div>

      <div class="row-fluid padd20-top-btm">
        <div class="span12 t-center">
          <p>Наш интернет магазин желает вам приятных и удачных покупок! Стремитесь к красоте и наилучшим результатам! Никогда не сдавайтесь и не ищите оправданий временным слабостям и недостаткам. Вместе мы достигнем желаемого! <br/>Спорт – наша жизнь!</p>
        </div>
      </div>
    </div>
  </div>