<div class="page-content">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <span class="divider">/</span></li>
            <li class="active">Блог о спорте</li>
          </ul>
        </div>
      </div>
      
      <div class="row-fluid blog">
        <div class="span9">
          <?php if(!empty($posts)): ?>
            <?php foreach ($posts as $key => $post): ?>
              <div class="row-fluid blog-post">
                <div class="span12">
                  <h2>
                    <span class="the-calendar">
                      <span class="the-date"><i class="icon-calendar"></i> <?php echo date('d/m/y', $post->time); ?></span>
                      <span class="the-comments"><i class="icon-comments"></i><?php echo count($post->comments); ?></span>
                    </span>
                    <a href="/blog/item/<?php echo $post->slug; ?>"><?php echo $post->title; ?></a>
                  </h2>
                  <hr>
                  <p><?php echo html_entity_decode($post->short); ?></p>
                  <p><a href="/blog/item/<?php echo $post->slug; ?>" class="btn btn-warning">Читать далее &raquo;</a></p>
                  <p class="meta-tags">
                    <i class="icon-tags"></i> 
                    <?php $last = end($post->tags); ?>
                    <?php foreach ($post->tags as $tag): ?>
                      <a href="/blog/tags/<?php echo $tag->slug ?>" <?php if(isset($currentTag) && $tag->slug == $currentTag): ?>class="active"<?php endif;?>><?php echo $tag->name; ?></a><?php if($tag != $last): ?>,<?php endif; ?> 
                    <?php endforeach; ?>
                  </p>
                </div>
              </div>
            <?php endforeach; ?>
          <?php else: ?>
            <h2>Увы, но постов нет</h2>
          <?php endif; ?>
          
          <?php if($pagination > 1): ?>
            <div class="row-fluid">
              <div class="span12">
                <div class="pagination pagination-centered">
                  <ul>
                  <li <?php if($current == 1): ?>class="disabled"<?php endif; ?>><a href="<?php echo $url; ?>/page/1">&laquo;</a></li>
                  <?php for($i=1; $i <= $pagination; $i++): ?>
                    <li <?php if($i == $current): ?>class="active"<?php endif; ?>><a href="<?php echo $url; ?>/page/<?php echo $i; ?>"><?php echo $i; ?></a></li>
                  <?php endfor; ?>
                  <li <?php if($current == $pagination): ?>class="disabled"<?php endif; ?>><a href="<?php echo $url; ?>/page/<?php echo $pagination; ?>">&raquo;</a></li>
                 </ul>
                </div>
              </div>
            </div>
        <?php endif; ?>
        </div>
        <div class="span3">
          <div class="row-fluid blog-sidebar">
            <div class="span12">
              <div class="widget">
                <h3><?php echo $widget['top']->title; ?></h3>
                <p><?php echo $widget['top']->body; ?></p>
              </div>
              
              <div class="widget">
                <h3><?php echo $widget['middle']->title; ?></h3>
                <p><?php echo $widget['middle']->body; ?></p>
              </div>
              <div class="widget widget-tags">
                <h3>Tags</h3>
                <ul>
                  <?php foreach ($tags as $tag): ?>                 
                    <li><a href="/blog/tags/<?php echo $tag->slug ?>"><?php echo $tag->name; ?></a></li>
                  <?php endforeach; ?>
                </ul>
              </div>
              <div class="widget">
                <h3><?php echo $widget['bottom']->title; ?></h3>
                <p><?php echo $widget['bottom']->body; ?></p>
              </div>
            </div>
          </div>
        </div>
      </div>      
    </div>
  </div>