<div id="catalogue">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <span class="divider">/</span></li>
            <li class="active"><?php if($type == 'category'): ?>Категории<?php else: ?>Производители<?php endif; ?></li>
          </ul>
        </div>
      </div>
      
      <div class="row-fluid">
        <div class="span12">
          <h2><?php if($type == 'category'): ?>Категории товаров<?php else: ?>Производители<?php endif; ?></h2>
          <p><?php if($type == 'category'): ?>Здесь собраны основные категориий товаров спортивного питания<?php else: ?>Здесь собраны ведущие производители товаров спортивного питания<?php endif; ?></p>
          <ul class="thumbnails">
            <?php $count = 1; ?>
            <?php if($type == 'category'): ?>
              <?php foreach($categories as $item): ?>
                <li class="<?php if($count == 1): ?>last<?php endif;?>  span3">
                  <div class="thumbnail">
                    <a href="/category/<?php echo $item->slug; ?>"><img src="/uploads/categories/<?php echo $item->img; ?>" alt="<?php echo $item->name; ?>" /></a>
                    <div class="caption-details">
                    <h3><?php echo $item->name; ?></h3>
                    </div>
                  </div>
                </li>
                <?php if($count == 4){ $count = 0; } ?>
                <?php $count++; ?>
                <?php endforeach; ?>
            <?php else: ?>
              <?php foreach($manufacturers as $item): ?>
                <li class="<?php if($count == 1): ?>last<?php endif;?> span3">
                  <div class="thumbnail">
                    <a href="/manufacturer/<?php echo $item->slug; ?>"><img src="/uploads/manufacturer/<?php echo $item->img; ?>" alt="<?php echo $item->name; ?>" /></a>
                    <div class="caption-details">
                    <h3><?php echo $item->name; ?></h3>
                    </div>
                  </div>
                </li>
                <?php if($count == 4){ $count = 0; } ?>
                <?php $count++; ?>
              <?php endforeach; ?>
            <?php endif; ?>

          </ul>
          
          <!-- <div class="pagination pagination-centered">
            <ul>
            <li class="disabled"><a href="#">&laquo;</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&raquo;</a></li>
           </ul>
          </div> -->
          
        </div>
      </div>
    </div>
  </div>