<div class="page-content contact">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <span class="divider">/</span></li>
            <li class="active">Контакты</li>
          </ul>
        </div>
      </div>
      
      <div class="row-fluid">
        <div class="span12 t-center">
          <h3>Телефоны для связи</h3>
          <p>
            <!-- (050) 598 - 62 - 98 <br/> -->
            (063) 726 - 12 - 17 <br/>
            (096) 876 - 16 - 55 <br/>
          </p>
        </div>
      </div>
      <div class="row-fluid padd20-top-btm">
        <div class="span5">
          <h3>обратная связь</h3>
          <form method="post" action="">
          <input type="text" id="name"     class="span12" placeholder="введите имя">
          <input type="text" id="email"    class="span12" placeholder="введите email">
          <input type="text" id="subject"  class="span12" placeholder="введите тему">
        </div>
        <div class="span7">
          <textarea id="body" class="span12" rows="10" placeholder="введите текст сообщения"></textarea>
          <input type="button" value="отправить" class="btn btn-warning btn-block btn-large">
          <img src="/img/ajax-loader.gif" style="display:none"/>
                <span class="successHandler">Сообщение успешно доставлено! Спасибо, что уделили время! </span>
                <span class="errorHandler">Произошла ошибка. Попробуйте позже</span>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    $(function(){
      $('input, textarea').on('focus', function(){
        $(this).removeClass('error');
      });
      $('input[type=button]').on('click', function(){
        var self          = this,
            nameElm       = $('#name'),
            emailElm      = $('#email'),
            subjectElm    = $('#subject'),
            bodyElm       = $('#body'),
            name          = $.trim(nameElm.val()),
            email         = $.trim(emailElm.val()),
            body          = $.trim(bodyElm.val()),
            subject       = $.trim(subjectElm.val()),
            validateEmail = function(email){
              var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
              return re.test(email);
            };
        
        if(!name){
          nameElm.addClass('error');
          nameElm.focus();
          return;
        }

        if(!email || !validateEmail(email)){
          emailElm.addClass('error');
          emailElm.focus();
          return;
        }

        if(!subject){
          subjectElm.addClass('error');
          subjectElm.focus();
          return;
        }

        if(!body){
          bodyElm.addClass('error');
          bodyElm.focus();
          return;
        }

        $(this).hide();
        $(this).next().show();
        
        $.ajax({
          url: '/contacts/send',
          type: 'post',
          data: {
            name: name,
            email: email,
            body: body,
            subject: subject,
          },
          success: function(){
            $('.successHandler').show();
            $(self).next().hide();
            nameElm.val('');
            emailElm.val('');
            bodyElm.val('');
            subjectElm.val('');

            _.delay(function(){ $('.successHandler').hide(); $(self).show(); }, 3000)
          },
          error: function(){
            $('.errorHandler').show();
            $(self).next().hide();
            _.delay(function(){ $('.errorHandler').hide(); $(self).show(); }, 3000)
          }
        })
      });
    });
  </script>