	
  <div class="page-content">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <span class="divider">/</span></li>
            <li class="active">Оплата и доставка</li>
          </ul>
        </div>
      </div>
      <div class="row-fluid padd20-top-btm">
        <div class="span4">
          <img src="/img/sss.png" alt="dodolan manuk catalogue">
        </div>
        <div class="span8">
          <h3>Доставка по Киеву</h3>
          <p>Доставка по Киеву осуществляется <b>курьером</b>! <br/>Ближайшее время и стоимость доставки уточняйте, пожалуйста, у наших специалистов</p>
        </div>
      </div>

      <div class="row-fluid padd20-top-btm">
        <div class="span8">
          <h3>Доставка по Украине</h3>
          <p>Доставка по Украине осуществляется  курьерской службой доставки "Новая Почта". <br/>С тарифами можно ознакомится на официальном сайте <a href="http://novaposhta.ua" target="blank">www.novaposhta.ua</a>. <br/>Другие способы доставки уточняйте с нашими специалистами.
          </p>
        </div>
        <div class="span4">
          <img src="/img/post.jpg" alt="dodolan manuk catalogue">
        </div>
      </div>

      <div class="row-fluid padd20-top-btm">
        <div class="span4">
          <img src="/img/cash.png" alt="dodolan manuk catalogue">
        </div>
        <div class="span8">
          <h3>Способы оплаты</h3>
          <p>
            - Наличными при получении<br>
            - Наложенным платежем при получении в отделении «Новой Почты».
            
          </p>
        </div>
      </div>
    </div>
  </div>