
  
  <div id="tagline">
    <div class="container">
      <div class="row">
        <div class="span12">
          <h2>Protein Lab - интернет-магазин</h2>
          <p>Добро пожаловать в интернет-магазин спортивного питания Protein Lab! <br/>Здесь Вы найдете все, что необходимо для полноценного и правильного питания во время изнурительных тренировок.</p>
        </div>
      </div>
    </div>
  </div>
  
  <div id="featured">
    <div class="container">
      <div class="row-fluid">
        <h2>Принципы</h2>
        <p>Это правила, которых мы придерживаемся в отношении нашего бизнеса и наших клиентов</p>
        <ul class="thumbnails">
          <li class="span4">
            <div class="featured-photos">
              <i class="icon-gift"></i>
            </div>
            <h3>отличное качество</h3>
            <p>Вся продукция доставляется исключительно из США. Никаких подделок или "кустарного" производства.</p>
          </li>
          <li class="span4">
            <div class="featured-photos">
              <i class="icon-dollar"></i>
            </div>
            <h3>демократичные цены</h3>
            <p>Гибкая ценовая политика никого не оставит равнодушным. </p>
          </li>
          <li class="span4">
            <div class="featured-photos">
              <i class="icon-envelope"></i>
            </div>
            <h3>обратная связь</h3>
            <p>Мы всегда открыты к предложениям наших клиентов и готовы работать над устранением недостатков.</p>
          </li>
        </ul>
      </div>
    </div>
  </div>
  
  <div id="catalogue">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <h2>Популярные товары</h2>
          <p>Самые популярные товары нашего магазина спортивных товаров</p>
          <ul class="thumbnails">
            <?php $count = 1; ?>
            <?php foreach($top8 as $product): ?>
              <li class="<?php if($count == 1): ?>last<?php endif;?>  span3">
                <div class="thumbnail">
                  <a href="/item/<?php echo $product->slug; ?>"><img src="/uploads/products/<?php echo $product->img['src']; ?>" alt="<?php echo $product->img['name']; ?>" /></a>
                  <div class="caption-details">
                  <h3><?php echo $product->name; ?></h3>
                  <span class="price">от <?php echo $product->minPrice; ?> грн.</span>
                  </div>
                </div>
              </li>
              <?php if($count == 4){ $count = 0; } ?>
              <?php $count++; ?>
            <?php endforeach; ?>      
          </ul>
        </div>
      </div>
    </div>
  </div>
  
  <!-- <div id="testimoni">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <p class="testimoni-icon"><i class="icon-quote-left"></i></p>
          <h3>Рекомендации</h3>
          <div class="row-fluid">
            <div class="span12">
              <div id="testi" class="carousel slide">
                <div class="carousel-inner">
                  <div class="item active">
                    <p class="testimoni-item">Замечательный магазин! Все доставляют вовремя. Качество - на ура!</p>
                    <h4>&#8212; Александр Артамошкин &#8212;</h4>
                  </div>
                  <div class="item">
                    <p class="testimoni-item">Приятные цены, хороший сервис, удобный сайт. </p>
                    <h4>&#8212; Григорий Солощенко &#8212;</h4>
                  </div>
                  <div class="item">
                    <p class="testimoni-item">Давно искал хороший магазин по спорт-питу. Кажется, я его нашел!</p>
                    <h4>&#8212; Олег Комаров &#8212;</h4>
                  </div>
                </div>
                <a class="left carousel-control" href="#testi" data-slide="prev">&lsaquo;</a>
                <a class="right carousel-control" href="#testi" data-slide="next">&rsaquo;</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> -->
  
  <div id="blog">
    <div class="container">
      <div class="row-fluid">
        <h2>Последние записи из блога</h2>
        <p>В нашем блоге Вы найдете огромное количество полезной информации о спорте и спортивном питании</p>
        <ul class="thumbnails">
          <?php foreach($posts as $post): ?>
            <li class="span4">
              <div class="blog-date">
                <i class="icon-calendar"></i>
                <span class="meta-date"><?php echo date('d', $post->time); ?></span>
                <span class="meta-month-year"><?php echo date('M Y', $post->time); ?></span>
              </div>
              <h3><a href="/blog/item/<?php echo $post->slug; ?>"><?php echo $post->title; ?></a></h3>
              <p><?php echo html_entity_decode($post->shortest); ?></p>
              <p><a href="/blog/item/<?php echo $post->slug; ?>" class="btn btn-warning">Читать далее &raquo;</a></p>
            </li>
          <?php endforeach; ?>
        </ul>
      </div>
    </div>
  </div>