<div class="page-content">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <span class="divider">/</span></li>
            <li class="active">Рекомендации</li>
          </ul>
        </div>
      </div>
      
      <div class="row-fluid testimoni">
        <h3 class="t-center">Рекомендации</h3>
        <hr>
        <ul class="thumbnails">
          <li class="span4">
          <div class="thumbnail">
            <div class="caption">
            <h3>&#8212; Александр А.</h3>
            <p>Замечательный магазин! Все доставляют вовремя. Качество - на ура!</p>
            </div>
          </div>
          </li>
          <li class="span4">
          <div class="thumbnail">
            <div class="caption">
            <h3>&#8212; Григорий С.</h3>
            <p>Приятные цены, хороший сервис, удобный сайт. </p>
            </div>
          </div>
          </li>
          <li class="span4">
          <div class="thumbnail">
            <div class="caption">
            <h3>&#8212; Олег К.</h3>
            <p>Давно искал хороший магазин по спорт-питу. Кажется, я его нашел!</p>
            </div>
          </div>
          </li>
          
        </ul>
      </div>
    </div>
  </div>